import { ModConfig } from '@/types/cms-types';
import { Quote } from 'lucide-react';

export const textWithQuoteConfig: ModConfig = {
  id: 'TextWithQuote',
  name: 'Texto com Citação',
  description: 'Seção de texto com citação bíblica ou frase inspiradora em destaque',
  category: 'content',
  icon: Quote,
  defaultProps: {
    title: 'Para quem o seu coração anseia?',
    content: 'Aqui no Recanto do Amor Misericordioso, acreditamos que a vida ganha seu mais profundo sentido quando nos abrimos à compaixão e à misericórdia.',
    quoteText: 'Não devias tu, igualmente, ter compaixão do teu conservo, como eu também tive misericórdia de ti?',
    quoteReference: 'Mateus 18:33',
    titleColor: 'primary',
    maxWidth: '4xl',
    bgColor: 'base-200',
    paddingY: 'lg',
    textAlign: 'center',
  },
  fields: [
    {
      name: 'title',
      label: 'Título',
      type: 'text',
      required: true,
      placeholder: 'Para quem o seu coração anseia?',
      description: 'Título da seção',
    },
    {
      name: 'content',
      label: 'Conteúdo',
      type: 'textarea',
      required: true,
      placeholder: 'Texto principal da seção...',
      description: 'Texto principal antes da citação',
    },
    {
      name: 'quoteText',
      label: 'Texto da Citação',
      type: 'textarea',
      required: false,
      placeholder: 'Citação inspiradora...',
      description: 'Texto da citação em destaque (deixe vazio para não exibir)',
    },
    {
      name: 'quoteReference',
      label: 'Referência da Citação',
      type: 'text',
      required: false,
      placeholder: 'Mateus 18:33',
      description: 'Referência bíblica ou autor da citação',
    },
    {
      name: 'titleColor',
      label: 'Cor do Título',
      type: 'select',
      options: [
        { value: 'primary', label: 'Principal (muda com o tema)' },
        { value: 'secondary', label: 'Secundário (muda com o tema)' },
        { value: 'accent', label: 'Destaque (muda com o tema)' },
      ],
      default: 'primary',
      description: 'Cor semântica do título',
    },
    {
      name: 'maxWidth',
      label: 'Largura do Conteúdo',
      type: 'select',
      options: [
        { value: 'sm', label: 'Muito Estreito' },
        { value: 'md', label: 'Estreito' },
        { value: 'lg', label: 'Médio-Estreito' },
        { value: 'xl', label: 'Médio' },
        { value: '2xl', label: 'Médio-Largo' },
        { value: '3xl', label: 'Largo' },
        { value: '4xl', label: 'Muito Largo (recomendado)' },
        { value: '5xl', label: 'Extra Largo' },
        { value: '6xl', label: 'Super Largo' },
      ],
      default: '4xl',
      description: 'Largura máxima do conteúdo',
    },
    {
      name: 'bgColor',
      label: 'Cor de Fundo',
      type: 'select',
      options: [
        { value: 'base-100', label: 'Fundo Claro' },
        { value: 'base-200', label: 'Fundo Médio' },
        { value: 'base-300', label: 'Fundo Escuro' },
      ],
      default: 'base-200',
      description: 'Cor de fundo da seção (muda com o tema)',
    },
    {
      name: 'paddingY',
      label: 'Espaçamento Vertical',
      type: 'select',
      options: [
        { value: 'sm', label: 'Pequeno' },
        { value: 'md', label: 'Médio' },
        { value: 'lg', label: 'Grande (recomendado)' },
        { value: 'xl', label: 'Extra Grande' },
      ],
      default: 'lg',
      description: 'Espaço acima e abaixo da seção',
    },
    {
      name: 'textAlign',
      label: 'Alinhamento do Texto',
      type: 'select',
      options: [
        { value: 'left', label: 'Esquerda' },
        { value: 'center', label: 'Centralizado' },
        { value: 'justify', label: 'Justificado' },
      ],
      default: 'center',
      description: 'Alinhamento do conteúdo',
    },
  ],
};
