import { ModConfig } from '@/types/cms-types';
import { ListChecks } from 'lucide-react';

export const qualitiesListConfig: ModConfig = {
  id: 'QualitiesList',
  name: 'Lista de Qualidades',
  description: 'Lista de requisitos, qualidades ou características com ícones de check',
  category: 'content',
  icon: ListChecks,
  defaultProps: {
    title: 'Quem Quer Caminhar Conosco?',
    items: [
      'Buscamos corações abertos à escuta e ao aprendizado contínuo.',
      'Almas que anseiam viver o Amor Misericordioso e o perdão.',
      'Pessoas dispostas à cura interior e ao autoconhecimento.',
      'Espíritos que desejam servir com amor aos mais necessitados.',
      'Quem busca a santidade na simplicidade do cotidiano.',
    ],
    titleColor: 'primary',
    iconColor: 'primary',
    maxWidth: '4xl',
    bgColor: 'base-200',
    paddingY: 'lg',
    textSize: 'lg',
    showIcons: true,
  },
  fields: [
    {
      name: 'title',
      label: 'Título',
      type: 'text',
      required: true,
      placeholder: 'Quem Quer Caminhar Conosco?',
      description: 'Título da seção',
    },
    {
      name: 'items',
      label: 'Itens da Lista',
      type: 'text-list-editor',
      required: true,
      description: 'Use os botões +/- para adicionar ou remover itens da lista.',
    },
    {
      name: 'showIcons',
      label: 'Exibir Ícones',
      type: 'checkbox',
      default: true,
      description: 'Mostrar ícones de check ao lado de cada item',
    },
    {
      name: 'iconColor',
      label: 'Cor dos Ícones',
      type: 'select',
      options: [
        { value: 'primary', label: 'Principal (muda com o tema)' },
        { value: 'secondary', label: 'Secundário (muda com o tema)' },
        { value: 'accent', label: 'Destaque (muda com o tema)' },
        { value: 'success', label: 'Sucesso (verde fixo)' },
      ],
      default: 'primary',
      description: 'Cor dos ícones de check',
    },
    {
      name: 'titleColor',
      label: 'Cor do Título',
      type: 'select',
      options: [
        { value: 'primary', label: 'Principal (muda com o tema)' },
        { value: 'secondary', label: 'Secundário (muda com o tema)' },
        { value: 'accent', label: 'Destaque (muda com o tema)' },
      ],
      default: 'primary',
      description: 'Cor semântica do título',
    },
    {
      name: 'textSize',
      label: 'Tamanho do Texto',
      type: 'select',
      options: [
        { value: 'sm', label: 'Pequeno' },
        { value: 'base', label: 'Normal' },
        { value: 'lg', label: 'Grande (recomendado)' },
        { value: 'xl', label: 'Extra Grande' },
      ],
      default: 'lg',
      description: 'Tamanho da fonte dos itens',
    },
    {
      name: 'maxWidth',
      label: 'Largura do Conteúdo',
      type: 'select',
      options: [
        { value: 'sm', label: 'Muito Estreito' },
        { value: 'md', label: 'Estreito' },
        { value: 'lg', label: 'Médio-Estreito' },
        { value: 'xl', label: 'Médio' },
        { value: '2xl', label: 'Médio-Largo' },
        { value: '3xl', label: 'Largo' },
        { value: '4xl', label: 'Muito Largo (recomendado)' },
        { value: '5xl', label: 'Extra Largo' },
        { value: '6xl', label: 'Super Largo' },
      ],
      default: '4xl',
      description: 'Largura máxima do conteúdo',
    },
    {
      name: 'bgColor',
      label: 'Cor de Fundo',
      type: 'select',
      options: [
        { value: 'base-100', label: 'Fundo Claro' },
        { value: 'base-200', label: 'Fundo Médio' },
        { value: 'base-300', label: 'Fundo Escuro' },
      ],
      default: 'base-200',
      description: 'Cor de fundo da seção (muda com o tema)',
    },
    {
      name: 'paddingY',
      label: 'Espaçamento Vertical',
      type: 'select',
      options: [
        { value: 'sm', label: 'Pequeno' },
        { value: 'md', label: 'Médio' },
        { value: 'lg', label: 'Grande (recomendado)' },
        { value: 'xl', label: 'Extra Grande' },
      ],
      default: 'lg',
      description: 'Espaço acima e abaixo da seção',
    },
  ],
};
