import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { ThemeProvider } from "@/components/ui/daisyui/theme-controller";
import { PropsNextThemes } from "@/components/ui/daisyui/theme-controller/theme.provider";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nextThemesProps: PropsNextThemes = {
    attribute: "class",
    defaultTheme: "system",
    enableSystem: true,
    disableTransitionOnChange: false,
  };

  return (
    <html suppressHydrationWarning lang="pt-br">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          lightTheme={"recanto-light"}
          darkTheme={"recanto-dark"}
          className="h-svh w-full"
          propsNextThemes={nextThemesProps}
        >
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
