import { ModConfig } from '@/types/cms-types';
import { Mail } from 'lucide-react';

export const vocationalContactFormConfig: ModConfig = {
  id: 'VocationalContactForm',
  name: 'Formulário Vocacional',
  description: 'Formulário de contato para discernimento vocacional com campos customizáveis',
  category: 'form',
  icon: Mail,
  defaultProps: {
    title: 'Queremos Conhecer Sua História',
    subtitle: '',
    buttonText: 'Quero Discernir Minha Vocação',
    buttonColor: 'primary',
    titleColor: 'secondary',
    maxWidth: 'md',
    bgColor: 'base-100',
    paddingY: 'lg',
    showName: true,
    showEmail: true,
    showPhone: true,
    showMessage: true,
  },
  fields: [
    {
      name: 'title',
      label: 'Título',
      type: 'text',
      required: true,
      placeholder: 'Queremos Conhecer Sua História',
      description: 'Título do formulário',
    },
    {
      name: 'subtitle',
      label: 'Subtítulo',
      type: 'textarea',
      required: false,
      placeholder: 'Texto explicativo opcional...',
      description: 'Texto descritivo abaixo do título (deixe vazio para não exibir)',
    },
    {
      name: 'buttonText',
      label: 'Texto do Botão',
      type: 'text',
      required: true,
      placeholder: 'Quero Discernir Minha Vocação',
      description: 'Texto do botão de envio',
    },
    {
      name: 'showName',
      label: 'Exibir Campo Nome',
      type: 'checkbox',
      default: true,
      description: 'Mostrar campo de nome no formulário',
    },
    {
      name: 'showEmail',
      label: 'Exibir Campo E-mail',
      type: 'checkbox',
      default: true,
      description: 'Mostrar campo de e-mail no formulário',
    },
    {
      name: 'showPhone',
      label: 'Exibir Campo Telefone',
      type: 'checkbox',
      default: true,
      description: 'Mostrar campo de telefone no formulário',
    },
    {
      name: 'showMessage',
      label: 'Exibir Campo Mensagem',
      type: 'checkbox',
      default: true,
      description: 'Mostrar campo de mensagem no formulário',
    },
    {
      name: 'buttonColor',
      label: 'Cor do Botão',
      type: 'select',
      options: [
        { value: 'primary', label: 'Principal (muda com o tema)' },
        { value: 'secondary', label: 'Secundário (muda com o tema)' },
        { value: 'accent', label: 'Destaque (muda com o tema)' },
      ],
      default: 'primary',
      description: 'Cor semântica do botão de envio',
    },
    {
      name: 'titleColor',
      label: 'Cor do Título',
      type: 'select',
      options: [
        { value: 'primary', label: 'Principal (muda com o tema)' },
        { value: 'secondary', label: 'Secundário (muda com o tema)' },
        { value: 'accent', label: 'Destaque (muda com o tema)' },
      ],
      default: 'secondary',
      description: 'Cor semântica do título',
    },
    {
      name: 'maxWidth',
      label: 'Largura do Formulário',
      type: 'select',
      options: [
        { value: 'sm', label: 'Pequeno' },
        { value: 'md', label: 'Médio (recomendado)' },
        { value: 'lg', label: 'Grande' },
        { value: 'xl', label: 'Extra Grande' },
      ],
      default: 'md',
      description: 'Largura máxima do formulário',
    },
    {
      name: 'bgColor',
      label: 'Cor de Fundo',
      type: 'select',
      options: [
        { value: 'base-100', label: 'Fundo Claro' },
        { value: 'base-200', label: 'Fundo Médio' },
        { value: 'base-300', label: 'Fundo Escuro' },
      ],
      default: 'base-100',
      description: 'Cor de fundo da seção (muda com o tema)',
    },
    {
      name: 'paddingY',
      label: 'Espaçamento Vertical',
      type: 'select',
      options: [
        { value: 'sm', label: 'Pequeno' },
        { value: 'md', label: 'Médio' },
        { value: 'lg', label: 'Grande (recomendado)' },
        { value: 'xl', label: 'Extra Grande' },
      ],
      default: 'lg',
      description: 'Espaço acima e abaixo da seção',
    },
  ],
};
