import { ModConfig } from '@/types/cms-types';

export const callToActionConfig: ModConfig = {
  id: 'CallToAction',
  name: 'Chamada para Ação (CTA)',
  description: 'Seção de CTA com título, descrição e botões de ação',
  icon: 'MousePointerClick',
  category: 'cta',
  props: [
    {
      name: 'title',
      label: 'Título',
      type: 'text',
      required: true,
      placeholder: 'Quer caminhar conosco?',
      description: 'Título da chamada para ação',
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: false,
      placeholder: 'Junte-se à missão do Recanto. Ajude-nos a espalhar o Amor Misericordioso.',
      description: 'Texto descritivo do CTA (opcional)',
    },
    {
      name: 'buttons',
      label: 'Botões',
      type: 'buttons-editor',
      required: true,
      default: [
        {
          text: 'Apoie nossa missão',
          url: '/doacoes',
          style: 'primary',
        },
        {
          text: 'Entre em contato',
          url: '/contatos',
          style: 'secondary',
        },
      ],
      description: 'Use os botões +/- para adicionar ou remover botões. Configure texto, link e estilo visualmente.',
    },
    {
      name: 'titleColor',
      label: 'Cor do Título',
      type: 'select',
      options: [
        { value: 'primary', label: 'Principal (muda com o tema)' },
        { value: 'secondary', label: 'Secundário (muda com o tema)' },
        { value: 'accent', label: 'Destaque (muda com o tema)' },
      ],
      default: 'primary',
      description: 'Cor semântica que se adapta ao tema escolhido',
    },
    {
      name: 'titleSize',
      label: 'Tamanho do Título',
      type: 'select',
      options: [
        { value: 'sm', label: 'Pequeno' },
        { value: 'md', label: 'Médio' },
        { value: 'lg', label: 'Grande' },
        { value: 'xl', label: 'Extra Grande (recomendado)' },
        { value: '2xl', label: 'Muito Grande' },
      ],
      default: 'xl',
      description: 'Tamanho da fonte do título',
    },
    {
      name: 'buttonSize',
      label: 'Tamanho dos Botões',
      type: 'select',
      options: [
        { value: 'xs', label: 'Extra Pequeno' },
        { value: 'sm', label: 'Pequeno' },
        { value: 'md', label: 'Médio (recomendado)' },
        { value: 'lg', label: 'Grande' },
      ],
      default: 'md',
      description: 'Tamanho dos botões de ação',
    },
    {
      name: 'bgColor',
      label: 'Cor de Fundo',
      type: 'select',
      options: [
        { value: 'base-100', label: 'Fundo Claro' },
        { value: 'base-200', label: 'Fundo Médio' },
        { value: 'base-300', label: 'Fundo Escuro' },
      ],
      default: 'base-100',
      description: 'Cor de fundo da seção (muda com o tema)',
    },
    {
      name: 'textAlign',
      label: 'Alinhamento',
      type: 'select',
      options: [
        { value: 'left', label: 'Esquerda' },
        { value: 'center', label: 'Centro' },
        { value: 'right', label: 'Direita' },
      ],
      default: 'center',
      description: 'Como o texto e botões ficam alinhados',
    },
    {
      name: 'maxWidth',
      label: 'Largura da Seção',
      type: 'select',
      options: [
        { value: '4xl', label: 'Estreita (ideal para texto)' },
        { value: '5xl', label: 'Média-Estreita' },
        { value: '6xl', label: 'Média (recomendado)' },
        { value: '7xl', label: 'Larga' },
        { value: 'full', label: 'Largura Total' },
      ],
      default: '6xl',
      description: 'Largura máxima do conteúdo na tela',
    },
    {
      name: 'paddingY',
      label: 'Espaçamento Vertical',
      type: 'select',
      options: [
        { value: 'sm', label: 'Pequeno' },
        { value: 'md', label: 'Médio' },
        { value: 'lg', label: 'Grande (recomendado)' },
        { value: 'xl', label: 'Extra Grande' },
      ],
      default: 'lg',
      description: 'Espaço acima e abaixo da seção',
    },
  ],
};
