import { ModConfig } from '@/types/cms-types';

export const heroStructureConfig: ModConfig = {
  id: 'HeroStructure',
  name: 'Hero Institucional',
  description: 'Hero com animação Lottie e citação bíblica, ideal para páginas institucionais',
  icon: 'Landmark',
  category: 'hero',
  props: [
    {
      name: 'title',
      label: 'Título Principal',
      type: 'text',
      required: true,
      placeholder: 'Nosso Recanto: Amor, Compaixão e Serviço',
      description: 'Título principal do hero',
    },
    {
      name: 'description',
      label: 'Descrição',
      type: 'textarea',
      required: true,
      multiline: true,
      placeholder: 'Paz e Unção! Somos uma família em Cristo...',
      description: 'Texto descritivo abaixo do título',
    },
    {
      name: 'animationUrl',
      label: 'Animação Lottie',
      type: 'animation-picker',
      required: true,
      description: 'Escolha uma animação da biblioteca ou envie uma URL personalizada',
    },
    {
      name: 'quote',
      label: 'Citação Bíblica',
      type: 'textarea',
      required: true,
      multiline: true,
      placeholder: 'Não devias tu também ter compaixão do teu conservo...',
      description: 'Texto da citação bíblica (sem aspas)',
    },
    {
      name: 'quoteReference',
      label: 'Referência Bíblica',
      type: 'text',
      required: true,
      placeholder: 'Mateus 18:33',
      description: 'Livro, capítulo e versículo',
    },
    {
      name: 'titleColor',
      label: 'Cor do Título',
      type: 'select',
      options: [
        { value: 'primary', label: 'Principal (muda com o tema)' },
        { value: 'secondary', label: 'Secundário (muda com o tema)' },
        { value: 'accent', label: 'Destaque (muda com o tema)' },
      ],
      default: 'primary',
      description: 'Cor semântica do título',
    },
    {
      name: 'quoteColor',
      label: 'Cor da Citação',
      type: 'select',
      options: [
        { value: 'primary', label: 'Principal (muda com o tema)' },
        { value: 'secondary', label: 'Secundário (muda com o tema)' },
        { value: 'accent', label: 'Destaque (muda com o tema)' },
        { value: 'info', label: 'Azul (fixo)' },
        { value: 'success', label: 'Verde (fixo)' },
        { value: 'warning', label: 'Amarelo (fixo)' },
      ],
      default: 'secondary',
      description: 'Cor semântica da citação',
    },
    {
      name: 'maxWidth',
      label: 'Largura do Conteúdo',
      type: 'select',
      options: [
        { value: '4xl', label: 'Estreita' },
        { value: '5xl', label: 'Média (recomendado)' },
        { value: '6xl', label: 'Larga' },
        { value: '7xl', label: 'Muito Larga' },
        { value: 'full', label: 'Largura Total' },
      ],
      default: '5xl',
      description: 'Largura máxima do conteúdo',
    },
    {
      name: 'bgColor',
      label: 'Cor de Fundo',
      type: 'select',
      options: [
        { value: 'base-100', label: 'Fundo Claro' },
        { value: 'base-200', label: 'Fundo Médio' },
        { value: 'base-300', label: 'Fundo Escuro' },
      ],
      default: 'base-100',
      description: 'Cor de fundo da seção (muda com o tema)',
    },
  ],
};
